### ISSUE TITLE
Object detection

### ISSUE THREAD

**Issue by 920666358** [VITA-Group/SLaK#11]
您好，您在论文中有做Object detection的实验，并在项目中提到可以用mmdetection框架做目标检测，请问可以更新下detection相关的代码？

**Comment by Shiweiliuiiiiiii** [comment]
Hi, we have added the code for the COCO object detection.

**Comment by freshn** [comment]
Hi, where can I find the base config '_base_/models/cascade_mask_rcnn_slak_fpn.py'?

**Comment by Shiweiliuiiiiiii** [comment]
You can find it [here](https://github.com/VITA-Group/SLaK/blob/main/detection/configs/_base_/models/cascade_mask_rcnn_slak_fpn.py). @freshn
