### ISSUE TITLE
Incorrect number of parameters

### ISSUE THREAD

**Issue by shashankskagnihotri** [VITA-Group/SLaK#12]
Dear Authors,
In the README.md the number of parameters mentioned for SLaK-T with 51x51 kernels is ~30M however, when I ran your eval code for Imagenet with your trained model, line 352 of main.py printed "number of params: 50703838" which is way more than 30M.
I saw the same issue with the SLaK-S model which in fact had 91131820 parameters in contrast to the ~55M mentioned in the file, and also SLaK-B which had 157950792 parameters in contrast to the ~95M mentioned.

So basically, the accuracies are matching but not the number of parameters to those mentioned.
So, is there a typing mistake in your file or am I missing something?

Just for reference the command is ran was:
python main.py --model SLaK_tiny --eval true \
--Decom True --kernel_size 51 49 47 13 5 --width_factor 1.3 \
--resume path/to/checkpoint \
--input_size 224 --drop_path 0.2 \
--data_path /path/to/imagenet-1k

And I changed SLaK_tiny to the appropriate model names and gave the correct paths for the models and the dataset.

**Comment by Shiweiliuiiiiiii** [comment]
Hi, Thanks for your interest and question. Our models are actually sparse models where a large portion of their parameters are zero. Thus, the reported parameter count refers to the total number of parameters that are non-zero. Specifically, we used 40% sparsity for all the models so the overall parameter count of SLaK-T is 50703838*60% ~= 30M.

**Comment by shashankskagnihotri** [comment]
Hi,
Thanks a lot for the quick reply. This makes sense. Just maybe a small suggestion, instead of writing it as #params, in this case calling it #non-zero params or #effective params would make it a more accurate table.

**Comment by Shiweiliuiiiiiii** [comment]
Thanks
