### ISSUE TITLE
use SLaK-T-31-checkpoint-best.pth  classification result is error

### ISSUE THREAD

**Issue by lvyan2001** [VITA-Group/SLaK#16]
python3 main.py --model SLaK_tiny --eval true \
--Decom True --kernel_size 51 49 47 13 5 --width_factor 1.3 \
--resume SLaK-T-31-checkpoint-best.pth \
--input_size 224 --drop_path 0.2 \
--data_path imagenet-1k

**result is error:**
Test:  [0/2]  eta: 0:00:05  loss: 6.4676 (6.4676)  acc1: 0.0000 (0.0000)  acc5: 0.0000 (0.0000)  time: 2.5371  data: 0.8399  max mem: 2273
Test:  [1/2]  eta: 0:00:01  loss: 6.4676 (6.8534)  acc1: 0.0000 (0.0000)  acc5: 0.0000 (0.0000)  time: 1.3323  data: 0.4200  max mem: 2273
Test: Total time: 0:00:02 (1.4327 s / it)
* Acc@1 0.000 Acc@5 0.000 loss 6.853
Accuracy of the network on 2 test images: 0.00000%

**Comment by Shiweiliuiiiiiii** [comment]
For SLaK-T-31, we need to set --kernel_size 31 29 27 13 5
