### ISSUE TITLE
Have you completely released the code of second paper?

### ISSUE THREAD

**Issue by qgh1223** [VITA-Group/SLaK#17]
Have you completely released the code of second paper?
How to run?

**Comment by qgh1223** [comment]
Training code for large-kernel distillation
Running as this part?

**Comment by Shiweiliuiiiiiii** [comment]
Thank you for your kind interest. Yes, the training code of large-to-small kernel distillation can be found here https://github.com/VITA-Group/SLaK#training-code-for-large-kernel-distillation
