### ISSUE TITLE
error: no suitable conversion function from "__half" to "float" exists

### ISSUE THREAD

**Issue by JonyJiang123** [VITA-Group/SLaK#2]
When I run "./setup.py install --user" script, I got this error.

**Comment by Shiweiliuiiiiiii** [comment]
It seems like a Version Incompatibility Error. Can you try to adjust your python version like [here](https://github.com/DingXiaoH/RepLKNet-pytorch/issues/34#issuecomment-1179652590)?

**Comment by pdh930105** [comment]
But, this SLaK supports python version is 3.8, is we required downgrade python version and reinstall library? and then if possible, can you upload your docker file please.

**Comment by Mhaiyang** [comment]
Hi, I met the same problem. I tried using python3.8 and python3.7. Both failed...

**Comment by Shiweiliuiiiiiii** [comment]
Hi all,

It seems the update of cutlass causes this issue. I have uploaded the one I am using [cutlass](https://github.com/VITA-Group/SLaK/tree/main/cutlass), which can be installed properly.

**Comment by Mhaiyang** [comment]
> Hi all,
> 
> It seems the update of cutlass causes this issue. I have uploaded the one I am using [cutlass](https://github.com/VITA-Group/SLaK/tree/main/cutlass), which can be installed properly.

Thanks! It worked!

**Comment by Shiweiliuiiiiiii** [comment]
Awesome. In this case I am closing this issue. Feel free to reopen it if needed.
