### ISSUE TITLE
sparsity means？

### ISSUE THREAD

**Issue by henbucuoshanghai** [VITA-Group/SLaK#7]
sparsity 的意思是 51*5，5*51 和5*5   三个并行代替51*51？   省参数，因此sparsity？

**Comment by Shiweiliuiiiiiii** [comment]
Sparsity means the weights in the kernel are sparse. In other words, there are many weights are zero in the kernel. Please refer to this paper for more information. https://arxiv.org/abs/2102.00554

**Comment by henbucuoshanghai** [comment]
not 51X51？ It is 51X5,5X51,and 5X5 together?

**Comment by Shiweiliuiiiiiii** [comment]
Yes, we attempt decompose one 51x51 kernels into two 51x5 anf 5x51 kernels.
