### ISSUE TITLE
stage内部51X5和5X51并行，然后经过1X1，继续经过1X1？

### ISSUE THREAD

**Issue by henbucuoshanghai** [VITA-Group/SLaK#8]
和Convnext单个模块一样？

**Comment by henbucuoshanghai** [comment]
把7X7换成二个51模块并行，后续1X1，1X1不变？

**Comment by Shiweiliuiiiiiii** [comment]
Yes. You are right.

**Comment by henbucuoshanghai** [comment]
tks, where is the code of 1*1 conv? i  can not find  them? tks

**Comment by Shiweiliuiiiiiii** [comment]
The pointwise conv is implemented with a linear layer the same as the original ConvNeXt paper.

**Comment by henbucuoshanghai** [comment]
ok
